name: PlatformIO CI

on:
  push:
    branches:
    - master
    paths:
      - 'firmware/*'

jobs:
  build:
    name: Build firmwares
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run PlatformIO
      working-directory: firmware
      run: |
        pwd
        platformio ci --lib="." --project-conf platformio.ini src/*
